# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d6ca3597f4c7685cd4bf65946700a5728b9698e53546c5b4cd340fee209ea87441378e0eb91ac2d15584235106c945e3d5c6b50d32d5898a634c935fe99a8d

test:
  secret_key_base: bd95ab5b74ae703e75b35ff4554cb6cb10fa51d9e88adca017550d8ec8e8334432568e18ea97f75e26741464c60db0743086d09c918493b184558ad2cb0e76d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
